builderscon/conf.builderscon.io

provision.mk

Add pip install requests

---

.travis.yml
app.wsgi
requirements.txt

Enable travis, fix errors

---

accept_language.py
app.wsgi
config.json.default
provision.mk

Pythonのコーディング規約であるところのPEP8に準拠する形でリファクタリングを行いました。

Refactoring pep8

---

README.md
config.json.default
provision.mk

今現在入ってなかったので、今後開発者が増えた時に私と同じところで躓かないように…。

Provision redis-server

---

views/index.tpl

[Screenshot](http://res.cloudinary.com/dlze0abrr/image/upload/v1469230596/2016-07-23_08h35_45_xyocku.png)

Main statement in Japanese on the index page

---

views/sponsors.tpl

Add appreciation comment for sponsors

---

app.wsgi
views/add_session.tpl
views/conference.tpl
views/index.tpl
views/layout/base.tpl
views/layout/conference.tpl
views/login.tpl
views/news.tpl
views/session_detail.tpl
views/sessions.tpl
views/sponsors.tpl

create conference specific base template

---

app.py

make sure to return *something*

---

app.py

bugfixです。ready for review (localで動作確認済み)です。

bugfix, full_slug belongs to session's stash, not conference

---

app.py

こんなエラーが出てきたので、以下を参考に変えました。
[StackOverflow - How to avoid RuntimeError: dictionary changed size during iteration error] (http://stackoverflow.com/questions/11941817/how-to-avoid-runtimeerror-dictionary-changed-size-during-iteration-error)
```
[2016-08-24 12:13:16,967] ERROR in app: Exception on /builderscon/tokyo/2016/cfp/input [POST]
Traceback (most recent call last):
...
...
File "app.py", line 581, in conference_cfp_input
for k in flask.session:
RuntimeError: dictionary changed size during iteration
```

Avoid dictionary changed size during iteration error

---

app.py

セッションタイトル・概要を日本語・英語両方入れたとき、片方だけ（英語）しか反映されていないようでした。スクリーンショットは日本語・英語両方でタイトルと概要を入力したときの確認画面ですが、
* セッションタイトル（日本語）
* セッション概要（日本語）
が空になっていました。

Add abstract and title from form data in non-English languages

---

templates/layout/base.tpl

ハンバーガー追加です。
ちゃんと、ページ毎にハンバーガーの中身は変わっていることも確認しました。

Add the humburger menu when width is less than 900px

---

app.py

This may be silly, but while we can be certain of a session's
association with a *user id*, we can't be sure if we always
have the up-to-date user information otherwise

refresh user for each request

---

templates/session/view.tpl

use height: auto.

---

templates/session/view.tpl

Show room if available

---

app/hooks.py

implement redirect_url

---

static/v2017/css/html.sp.css

Reverts builderscon/conf.builderscon.io#217

Revert "change background color"

---

app/filters.py
templates/session/view.tpl

get ogp from video thumbnail

---

templates/layout/base.tpl

Properly fill twitter card fields

---

templates/v2017/session/edit.html

fixes builderscon/admin.builderscon.io#66

Apply {% with %} to form_scripts

---

templates/v2017/cfp/done.html

Use raw conference, not input.conference

---

static/v2017/css/html.pc.css

- インデントでタブとスペースが混在していたので、スペースx2に統一しつつ全体をリフォーマット
- `!important` が書かれている位置がちょっと違う箇所があったので修正
- `<h1 class="title">` がコンテンツに被ってしまうような位置に存在していたので、  
本来あるべき位置に近付けました。（ `<em>` と同様に、画面左側に90度回転して配置。cssの都合上、 `<em>` とは中心点の位置が50%ずれています。以下画像参照）  
コンテンツに被る位置ではないので、 `pointer-events: none;` は指定していません。

Topic/v2017: Update static/v2017/css/html.pc.css
